### ISSUE TITLE
Where to get Basic Token from

### ISSUE THREAD

**Issue by yannickdoteu** [vfurmane/42cal#1]
Hey!

I am trying to use your app but I don't know where to get a "Basic token" from. Could you help me with that?

![image](https://github.com/user-attachments/assets/36ac0016-bee5-48dd-b7a5-0c8e9c50cf5b)

I have used your app before and it worked really nice!

**Comment by vfurmane** [comment]
Hi, answering after seeing your DM. :wave: 

The Basic token is unique to the hosted instance at https://api.42cal.valfur.fr. To prevent leaking 42 data, it is mandatory to get one. However, you cannot generate one at the moment. You may find the only available token on the school's Slack (where I first talked about the project).

I cannot link the message here for privacy reasons too haha. :slightly_smiling_face:
